apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auditflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dev.auditflow.dilipsecops.blog
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: auditflow-backend
            port:
              number: 4000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: auditflow-frontend
            port:
              number: 80
